### ISSUE TITLE
bug in Induction.py (Collection format)

### ISSUE THREAD

**Issue by PallaviBagga** [ZhengyaoJiang/GradientInduction#1]
In induction.py file, line 131, 

        return tape.gradient(loss_value, self.rule_weights.values())

should be replaced by 

        return tape.gradient(loss_value, list(self.rule_weights.values()))

otherwise the 
TypeError is raised because of the odict_values.

**Comment by PallaviBagga** [comment]
How do you set the threshold value for the weights in line 81 of file induction.py?

**Comment by ZhengyaoJiang** [comment]
You are right, thanks.

Edit:
By the way, I guess you get this error because you are in the Python3 environment.
