### ISSUE TITLE
Output (Generalized Logic Program)

### ISSUE THREAD

**Issue by PallaviBagga** [ZhengyaoJiang/GradientInduction#3]
Is there any way that this program generalizes the logic program?

For example, after executing agent.train(), we only get the weight values, and that also for clauses with ground atoms like 
predecessor(0,1):-succ(1,2),succ(2,0)
predecessor(0,1):-predecessor(1,1),predecessor(0,0),

However, the paper "learning explanatory rules from noisy data" is meant for generating clauses or rules, in other words a logical program in a generalized way (as per my knowledge), such as 
predecessor(X,Y):-Successor(Y,X)  
which is easy to interpret unlike the neural networks.

**Comment by ZhengyaoJiang** [comment]
> which is easy to interpret unlike the neural networks.

I used the integer to represent variables. String to represent entities (terms). In the latest version it when print the rules it will be translated to "predecessor(X,Y):-Successor(Y,X)" automatically.
